#!/usr/bin/env python
#
# License: BSD
#   https://raw.github.com/robotics-in-concert/rocon_tutorials/master/turtle_race_controllers/LICENSE
#
##############################################################################
# Imports
##############################################################################

import sys
import argparse
#import re
import roslib 
roslib.load_manifest('turtle_race_controllers')
import rospy
import tf
import turtle_race_controllers

##############################################################################
# Functions
##############################################################################
    
def parse_arguments():
    parser = argparse.ArgumentParser(description='Starts the turtle race!')
    args = parser.parse_args()
    return args

##############################################################################
# Main
##############################################################################

if __name__ == '__main__':
    
    rospy.init_node('turtle_race')
    args = parse_arguments()
    race_controller = turtle_race_controllers.RaceController()
    rospy.spin()
    race_controller.shutdown()
